# Generated by Django 3.0.5 on 2020-07-20 07:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import scraper_etsy.items.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.PositiveIntegerField(default=64, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Limit of listings')),
                ('count_tags', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Count of tags')),
                ('sales', models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Count of sales')),
                ('year_store_base', models.PositiveIntegerField(default=2016, validators=[django.core.validators.MinValueValidator(1970), scraper_etsy.items.models.validate_year], verbose_name='Year store base')),
                ('countries', django_countries.fields.CountryField(default=['US', 'CA'], max_length=746, multiple=True)),
            ],
            options={
                'unique_together': {('limit', 'count_tags', 'sales', 'year_store_base', 'countries')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=500, verbose_name='h1')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Title')),
                ('year_store_base', models.DateField(verbose_name='Shop opening date')),
                ('sales', models.IntegerField(verbose_name='Total sales')),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('url', models.URLField(max_length=1000, verbose_name='Url')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', related_query_name='tag', to='items.Item')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(null=True, verbose_name='Status code of server')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Done')], default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(auto_now=True)),
                ('search', models.CharField(max_length=500, verbose_name='Search phrase')),
                ('url', models.URLField(max_length=1000, verbose_name='Url')),
                ('level', models.PositiveIntegerField(default=0)),
                ('filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Filter', verbose_name='Filter')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='items.Request')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.AddField(
            model_name='item',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item', related_query_name='item', to='items.Request'),
        ),
        migrations.AddField(
            model_name='item',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='items.Shop'),
        ),
    ]
