# Generated by Django 3.0.5 on 2020-06-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200613_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='url',
            field=models.URLField(max_length=1000, verbose_name='Url'),
        ),
    ]
