# Generated by Django 3.0.5 on 2020-08-03 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20200801_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='sales',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Count of sales'),
        ),
    ]
