# Generated by Django 3.0.5 on 2020-07-13 06:37

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import scraper_etsy.items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20200708_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.PositiveIntegerField(default=64, verbose_name='Limit of listings')),
                ('count_tags', models.PositiveIntegerField(default=10, verbose_name='Count of tags')),
                ('sales', models.PositiveIntegerField(default=1000, verbose_name='Count of sales')),
                ('year_store_base', models.PositiveIntegerField(validators=[scraper_etsy.items.models.validate_year], verbose_name='Year store base')),
                ('countries', django_countries.fields.CountryField(default=['US', 'CA'], max_length=746, multiple=True)),
            ],
            options={
                'unique_together': {('limit', 'count_tags', 'sales', 'year_store_base', 'countries')},
            },
        ),
        migrations.AddField(
            model_name='request',
            name='filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Filter', verbose_name='Filter'),
        ),
    ]
