# Generated by Django 3.0.5 on 2020-07-13 15:54

from django.db import migrations, models
import scraper_etsy.items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20200713_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='year_store_base',
            field=models.PositiveIntegerField(default=2016, validators=[scraper_etsy.items.models.validate_year], verbose_name='Year store base'),
        ),
    ]
