# Generated by Django 3.0.5 on 2020-06-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20200622_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shops', related_query_name='shop', to='items.Request'),
            preserve_default=False,
        ),
    ]
