# Generated by Django 3.0.5 on 2021-04-12 10:06

import django.core.validators
from django.db import migrations, models
import scraper_etsy.items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20200803_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='count_tags',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Count of tags'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='sales',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Count of sales'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='year_store_base',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(1970), scraper_etsy.items.models.validate_year], verbose_name='Year store base'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='year_store_base',
            field=models.DateField(null=True, verbose_name='Shop opening date'),
        ),
    ]
