# Generated by Django 3.0.5 on 2020-07-13 18:13

import django.core.validators
from django.db import migrations, models
import scraper_etsy.items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20200713_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='count_tags',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Count of tags'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='limit',
            field=models.PositiveIntegerField(default=64, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Limit of listings'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='sales',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Count of sales'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='year_store_base',
            field=models.PositiveIntegerField(default=2016, validators=[django.core.validators.MinValueValidator(1970), scraper_etsy.items.models.validate_year], verbose_name='Year store base'),
        ),
    ]
