# Generated by Django 3.0.5 on 2020-07-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20200713_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='started_at',
            new_name='year_store_base',
        ),
    ]
