# Generated by Django 3.0.5 on 2020-07-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20200714_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='ended_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
